### ISSUE TITLE
Question: what are "cancel functions" for?

### ISSUE THREAD

**Issue by jamesplease** [conorhastings/use-reducer-with-side-effects#22]
Yo! I'm pretty familiar with the dispatch/state side of this lib now, but I wanted to learn more about the side effects portion, so I was reading through the code and noticed the idea of "cancel functions", which are functions that can be returned from side effects.

Do you have a tl;dr or an example of how those might be used?

**Comment by jamesplease** [comment]
nvm I think I get it. The `cancelFn`s of the previous set of effects are called _before_ the new set are run. So you can use it to, say, cancel a request. Is that right?

**Comment by conorhastings** [comment]
yeah, that's exactly . right, cancel might . not even be the right word. but that was the . use case for implementation, a simple example . i have around is just mashing the . multiply after 5 seconds button and seeing thtat it only multiplies once -- https://codesandbox.io/s/angry-bouman-rc2x6

**Comment by jamesplease** [comment]
Okay, cool, I see. Thanks for sharing the CodeSandbox, it was helpful!
